[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

  [[module.imports]]
    path = "github.com/rymut/hugo-turing/hugo-turing-markdown-theme"
  [[module.imports]]
    path = "github.com/mrmierzejewski/hugo-theme-console"
  [[module.imports]]
    path = "github.com/Gioni06/terminalcss"
    [[module.imports.mounts]]
      source = "lib/"
      target = "assets/turing/console-theme/css/"
