baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

  [[module.imports]]
    path = "github.com/rymut/hugo-turing/hugo-turing-raw"
