############################
## Navbar
############################

main:
- name: ":~"
  url: /
  weight: 10
  params:
    logo: true
- name: features/
  url: /features/
  weight: 20
- name: about/
  url: /about/
  weight: 15
- name: github/
  url: /github/
  weight: 50
