[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

  [[module.imports]]
    path = 'github.com/rymut/hugo-turing/hugo-turing-type-json'

  [[module.imports]]
    path = 'github.com/rymut/hugo-turing/hugo-turing-type-html'

  [[module.mounts]]
    source = "layouts"
    target = "layouts"
